var app = new Vue({
    el:'#app',
    data:{
        columns:[
            {
                title:'姓名',
                key:'name',
                width:500
            },
            {
                title:'年龄',
                key:'age',
                sortable:true
            },
            {
                title:'出生日期',
                key:'birthday',
                sortable:true
            },
            {
                title:'地址',
                key:'address',
            },
        ],
        data:[  
            {
                name:'刘臻',
                age:18,
                birthday:'1995-06-26',
                address:'北京市朝阳区芍药居'
            },
            {
                name:'王小明',
                age:19,
                birthday:'1990-06-26',
                address:'北京市朝阳区芍药居'
            },
            {
                name:'雒雒',
                age:10,
                birthday:'1995-02-26',
                address:'北京市朝阳区芍药居'
            },
            {
                name:'王晓红',
                age:20,
                birthday:'1995-03-26',
                address:'北京市朝阳区芍药居'
            },
        ]
    },
    methods: {
        handleAddData(){
            this.data.push({
                name:'王小二',
                age:33,
                birthday:'1999-03-26',
                address:'北京市朝阳区芍药居'
            });
        }
    }
});
